version: "3.8"
services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir
    ports:
      - "8080:8080"
    environment:
      - hapi.fhir.fhir_version=R4
    restart: unless-stopped